import imgPlaceholder from './../images/video-movie-placeholder-image-grey.png';

const user = {
  name: 'Константин',
  email: 'pochta@yandex.ru',
};

const MoviesMock = [
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: '33 слова о дизайне',
    nameEN: 'asd',
    movieId: '1',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 1700,
    image: imgPlaceholder,
    nameRU: 'Киноальманах «100 лет дизайна»',
    nameEN: 'asd',
    movieId: '2',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'В погоне за Бенкси',
    nameEN: 'asd',
    movieId: '3',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Баския: Взрыв реальности',
    nameEN: 'asd',
    movieId: '4',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 1700,
    image: imgPlaceholder,
    nameRU: 'Бег это свобода',
    nameEN: 'asd',
    movieId: '5',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Книготорговцы',
    nameEN: 'asd',
    movieId: '6',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Когда я думаю о Германии ночью',
    nameEN: 'asd',
    movieId: '7',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 1700,
    image: imgPlaceholder,
    nameRU: 'Gimme Danger: История Игги и The Stooges',
    nameEN: 'asd',
    movieId: '8',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Дженис: Маленькая девочка грустит',
    nameEN: 'asd',
    movieId: '9',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Соберись перед прыжком',
    nameEN: 'asd',
    movieId: '10',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Пи Джей Харви: A dog called money',
    nameEN: 'asd',
    movieId: '11',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'По волнам: Искусство звука в кино',
    nameEN: 'asd',
    movieId: '12',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'По волнам: Искусство звука в кино',
    nameEN: 'asd',
    movieId: '13',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'По волнам: Искусство звука в кино',
    nameEN: 'asd',
    movieId: '14',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
];

const MoviesSavedMock = [
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: '33 слова о дизайне',
    nameEN: 'asd',
    movieId: '1',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  // {
  //   duration: 1700,
  //   image: imgPlaceholder,
  //   nameRU: 'Киноальманах «100 лет дизайна»',
  //   nameEN: 'asd',
  //   movieId: '2',
  // trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  // },
  // {
  //   duration: 5315,
  //   image: imgPlaceholder,
  //   nameRU: 'В погоне за Бенкси',
  //   nameEN: 'asd',
  //   movieId: '3',
  // trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  // },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Баския: Взрыв реальности',
    nameEN: 'asd',
    movieId: '4',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 1700,
    image: imgPlaceholder,
    nameRU: 'Бег это свобода',
    nameEN: 'asd',
    movieId: '5',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Книготорговцы',
    nameEN: 'asd',
    movieId: '6',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Когда я думаю о Германии ночью',
    nameEN: 'asd',
    movieId: '7',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  // {
  //   duration: 1700,
  //   image: imgPlaceholder,
  //   nameRU: 'Gimme Danger: История Игги и The Stooges',
  //   nameEN: 'asd',
  //   movieId: '8',
  // trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  // },
  // {
  //   duration: 5315,
  //   image: imgPlaceholder,
  //   nameRU: 'Дженис: Маленькая девочка грустит',
  //   nameEN: 'asd',
  //   movieId: '9',
  // trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  // },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Соберись перед прыжком',
    nameEN: 'asd',
    movieId: '10',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'Пи Джей Харви: A dog called money',
    nameEN: 'asd',
    movieId: '11',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
  {
    duration: 5315,
    image: imgPlaceholder,
    nameRU: 'По волнам: Искусство звука в кино',
    nameEN: 'asd',
    movieId: '12',
    trailerLink: 'https://youtu.be/dQw4w9WgXcQ?si=ZFlEKucAl-jxjpR8',
  },
];

export { user, MoviesMock, MoviesSavedMock };
